### ISSUE TITLE
关于Subset中数目的问题

### ISSUE THREAD

**Issue by vokkko** [zysxmu/DFSQ#1]
作者你好，我想问下Distribution-Flexible Subset Quantization for Post-Quantizing Super-Resolution Networks这篇文章中Subset中的数目为107这个是怎么算出来的？对于原论文中陈述“the value 0.8125 in the universal set is obtained by averaging the sum of 0 from the first word set, 2−2 from the second word set, and 1s from the third and fourth word sets.”应该为（0+2^-2+1+1）/4 =0.5625 而非0.8125

**Comment by zysxmu** [comment]
抱歉这么晚回复！
那个subset是我们算出来后，然后去了一个重复搞出来的。

后面这个是我们的typo，我们会在未来的版本进行改进！
